export const theme = {
    colors: {
        primary: '#15803D',
            primaryDark: '#166534',
                primaryLight: '#DCFCE7',
                    background: '#F4F7F5',
                        surface: '#FFFFFF',
                            border: '#E5E7EB',
                                textPrimary: '#1F2937',
                                    textSecondary: '#6B7280',
                                        danger: '#DC2626',
                                            warning: '#CA8A04',
                                                success: '#16A34A',
                                                    info: '#2563EB',
                                                        shadow: 'rgba(0,0,0,0.08)',
                                                          },
                                                            fontFamily: 'Cairo',
                                                              fontSize: {
                                                                  appTitle: '26px',
                                                                      pageTitle: '22px',
                                                                          cardTitle: '18px',
                                                                              body: '16px',
                                                                                  small: '14px',
                                                                                      financial: '24px',
                                                                                        },
                                                                                          spacing: {
                                                                                              xs: '4px',
                                                                                                  sm: '8px',
                                                                                                      md: '12px',
                                                                                                          lg: '16px',
                                                                                                              xl: '24px',
                                                                                                                  xxl: '32px',
                                                                                                                    },
                                                                                                                      borderRadius: {
                                                                                                                          input: '12px',
                                                                                                                              button: '12px',
                                                                                                                                  card: '18px',
                                                                                                                                      dialog: '20px',
                                                                                                                                        },
                                                                                                                                          headerHeight: '60px',
                                                                                                                                            bottomNavHeight: '64px',
                                                                                                                                            } as const;
