import { useState } from 'react';
import { useStore } from '@/store';
import { usePreventLeave } from '@/hooks/usePreventLeave';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import Dialog from '@/components/ui/Dialog';
import EmptyState from '@/components/ui/EmptyState';
import { Plus, Edit2, Trash2, Wallet } from 'lucide-react';

const fmt = (n: number) => Math.round(n).toLocaleString('en-US');
const dt = (d: string) => new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: '2-digit', day: '2-digit' });

export default function CashBoxes() {
  const s = useStore();
    const currency = s.settings?.currency || 'ريال يمني';
      const [open, setOpen] = useState(false);
        const [edit, setEdit] = useState<any>(null);
          const [f, setF] = useState({ name: '' });
            const [selectedBoxId, setSelectedBoxId] = useState(s.cashBoxes[0]?.id || '');
              const [hasChanges, setHasChanges] = useState(false);

                usePreventLeave(hasChanges);

                  const selectedBox = s.cashBoxes.find((b: any) => b.id === selectedBoxId);
                    const boxMovements = selectedBoxId ? s.cashMovements.filter((m: any) => m.cashBoxId === selectedBoxId).reverse() : [];

                      const reset = () => { setF({ name: '' }); setEdit(null); setHasChanges(false); };
                        const openAdd = () => { reset(); setOpen(true); };

                          const openEdit = (b: any) => {
                              setEdit(b);
                                  setF({ name: b.name });
                                      setHasChanges(true);
                                          setOpen(true);
                                            };

                                              const handleChange = (field: string, value: string) => {
                                                  setF({ ...f, [field]: value });
                                                      setHasChanges(true);
                                                        };

                                                          const save = () => {
                                                              if (!f.name) return;
                                                                  if (edit) s.updateCashBox(edit.id, { name: f.name });
                                                                      else s.addCashBox({ id: '', name: f.name, balance: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
                                                                          setOpen(false); reset();
                                                                            };

                                                                              const handleClose = () => {
                                                                                  if (hasChanges && !confirm('لديك تغييرات غير محفوظة. هل تريد المغادرة؟')) return;
                                                                                      setOpen(false); reset();
                                                                                        };

                                                                                          const del = (b: any) => {
                                                                                              if (b.id === 'default-cash-box') { alert('لا يمكن حذف الصندوق الرئيسي.'); return; }
                                                                                                  const hasMovements = s.cashMovements.some((m: any) => m.cashBoxId === b.id);
                                                                                                      if (hasMovements) { alert('لا يمكن حذف الصندوق لوجود حركات مالية مرتبطة به. يمكنك تعديل الاسم فقط.'); return; }
                                                                                                          if (confirm('سيتم نقل الصندوق إلى سلة المحذوفات. متابعة؟')) {
                                                                                                                s.deleteCashBox(b.id);
                                                                                                                      if (selectedBoxId === b.id) setSelectedBoxId(s.cashBoxes[0]?.id || '');
                                                                                                                          }
                                                                                                                            };

                                                                                                                              return (
                                                                                                                                  <div className="page-container">
                                                                                                                                        <div className="flex items-center justify-between mb-4">
                                                                                                                                                <h1 className="page-title mb-0">الصناديق</h1>
                                                                                                                                                        <Button onClick={openAdd}><Plus size={20} />إضافة</Button>
                                                                                                                                                              </div>

                                                                                                                                                                    {/* قائمة منسدلة لاختيار الصندوق */}
                                                                                                                                                                          <div className="mb-4">
                                                                                                                                                                                  <label className="block text-sm font-semibold mb-1">اختر الصندوق</label>
                                                                                                                                                                                          <select value={selectedBoxId} onChange={e => setSelectedBoxId(e.target.value)} className="input-field">
                                                                                                                                                                                                    {s.cashBoxes.map((b: any) => <option key={b.id} value={b.id}>{b.name}</option>)}
                                                                                                                                                                                                            </select>
                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                        {/* بطاقة الصندوق المحدد */}
                                                                                                                                                                                                                              {selectedBox && (
                                                                                                                                                                                                                                      <Card accent className="mb-4">
                                                                                                                                                                                                                                                <div className="flex items-start justify-between">
                                                                                                                                                                                                                                                            <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                          <Wallet size={24} className="text-primary" />
                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                        <h3 className="text-card-title">{selectedBox.name}</h3>
                                                                                                                                                                                                                                                                                                                        {(() => {
                                                                                                                                                                                                                                                                                                                                          const status = selectedBox.balance > 0 ? 'عليه' : selectedBox.balance < 0 ? 'له' : 'متزن';
                                                                                                                                                                                                                                                                                                                                                            const color = selectedBox.balance > 0 ? 'text-danger' : selectedBox.balance < 0 ? 'text-success' : 'text-info';
                                                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                                                                  <p className={`text-financial ${color}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                        {fmt(Math.abs(selectedBox.balance))} <span className="text-small">{currency}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <span className="text-small mr-1">({status})</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    })()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => openEdit(selectedBox)} className="flex items-center gap-1 px-3 py-1.5 bg-info/10 text-info rounded-btn text-small font-semibold"><Edit2 size={16} />تعديل</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {selectedBox.id !== 'default-cash-box' && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => del(selectedBox)} className="flex items-center gap-1 px-3 py-1.5 bg-danger/10 text-danger rounded-btn text-small font-semibold"><Trash2 size={16} />حذف</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* آخر العمليات */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-card-title mb-3">آخر العمليات</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {boxMovements.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <EmptyState message="لا توجد عمليات" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {boxMovements.map((m: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Card key={m.id} className="!p-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-small font-semibold">{m.description}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-small text-text-secondary">{dt(m.createdAt)}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-left">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <span className={`text-financial ${m.type === 'deposit' ? 'text-success' : 'text-danger'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {m.type === 'deposit' ? '+' : '-'}{fmt(m.amount)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-small text-text-secondary mr-1">{currency}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Dialog open={open} onClose={handleClose} title={edit ? 'تعديل صندوق' : 'إضافة صندوق'}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-3 pb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Input label="اسم الصندوق" value={f.name} onChange={e => handleChange('name', e.target.value)} autoComplete="off" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button fullWidth onClick={save}>{edit ? 'تحديث' : 'حفظ'}</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Dialog>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }