import { useState } from 'react';
import { useStore } from '@/store';
import { usePreventLeave } from '@/hooks/usePreventLeave';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import SearchInput from '@/components/ui/SearchInput';
import Dialog from '@/components/ui/Dialog';
import EmptyState from '@/components/ui/EmptyState';
import { Plus, Edit2, Trash2, Receipt } from 'lucide-react';

const fmt = (n: number) => Math.round(n).toLocaleString('en-US');
const dt = (d: string) => new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: '2-digit', day: '2-digit' });

const expenseTypes = ['إيجارات', 'رواتب موظفين', 'كهرباء', 'مصاريف أخرى'];

export default function Expenses() {
  const s = useStore();
    const currency = s.settings?.currency || 'ريال يمني';
      const [search, setSearch] = useState('');
        const [open, setOpen] = useState(false);
          const [edit, setEdit] = useState<any>(null);
            const [f, setF] = useState({ title: 'مصاريف أخرى', amount: '', cashBoxId: 'default-cash-box', date: new Date().toISOString().split('T')[0], notes: '' });
              const [hasChanges, setHasChanges] = useState(false);

                usePreventLeave(hasChanges);

                  const filtered = [...s.expenses].reverse().filter((e: any) => e.title.includes(search));

                    const reset = () => {
                        setF({ title: 'مصاريف أخرى', amount: '', cashBoxId: 'default-cash-box', date: new Date().toISOString().split('T')[0], notes: '' });
                            setEdit(null); setHasChanges(false);
                              };
                                const openAdd = () => { reset(); setOpen(true); };

                                  const openEdit = (e: any) => {
                                      setEdit(e);
                                          setF({ title: e.title, amount: e.amount.toString(), cashBoxId: e.cashBoxId, date: e.date, notes: e.notes || '' });
                                              setHasChanges(true);
                                                  setOpen(true);
                                                    };

                                                      const handleChange = (field: string, value: string) => {
                                                          setF({ ...f, [field]: value });
                                                              setHasChanges(true);
                                                                };

                                                                  const save = () => {
                                                                      if (!f.amount) return;
                                                                          const data = { title: f.title, amount: +f.amount, cashBoxId: f.cashBoxId, date: f.date, notes: f.notes };
                                                                              if (edit) s.updateExpense(edit.id, data);
                                                                                  else s.addExpense({ ...data, id: '', createdAt: new Date().toISOString() });
                                                                                      setOpen(false); reset();
                                                                                        };

                                                                                          const handleClose = () => {
                                                                                              if (hasChanges && !confirm('لديك تغييرات غير محفوظة. هل تريد المغادرة؟')) return;
                                                                                                  setOpen(false); reset();
                                                                                                    };

                                                                                                      const del = (id: string) => {
                                                                                                          if (confirm('سيتم نقل المصروف إلى سلة المحذوفات. متابعة؟')) s.deleteExpense(id);
                                                                                                            };

                                                                                                              const totalFiltered = filtered.reduce((sum: number, e: any) => sum + e.amount, 0);
                                                                                                                const cashBoxName = (id: string) => s.cashBoxes.find((b: any) => b.id === id)?.name || '';

                                                                                                                  return (
                                                                                                                      <div className="page-container">
                                                                                                                            <div className="flex items-center justify-between mb-4">
                                                                                                                                    <h1 className="page-title mb-0">المصروفات</h1>
                                                                                                                                            <Button onClick={openAdd}><Plus size={20} />إضافة</Button>
                                                                                                                                                  </div>

                                                                                                                                                        <SearchInput value={search} onChange={setSearch} placeholder="بحث عن مصروف..." />

                                                                                                                                                              {filtered.length > 0 && (
                                                                                                                                                                      <Card accent className="mb-4">
                                                                                                                                                                                <div className="flex justify-between items-center">
                                                                                                                                                                                            <span className="text-small text-text-secondary">إجمالي المصروفات</span>
                                                                                                                                                                                                        <span className="text-financial text-danger">{fmt(totalFiltered)} <span className="text-small">{currency}</span></span>
                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                          </Card>
                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                      {filtered.length === 0 ? <EmptyState message="لا توجد مصروفات" /> : (
                                                                                                                                                                                                                                              <div className="space-y-3">
                                                                                                                                                                                                                                                        {filtered.map((e: any) => (
                                                                                                                                                                                                                                                                    <Card key={e.id} accent>
                                                                                                                                                                                                                                                                                  <div className="flex items-start justify-between">
                                                                                                                                                                                                                                                                                                  <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                    <Receipt size={20} className="text-danger" />
                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                          <h3 className="font-semibold">{e.title}</h3>
                                                                                                                                                                                                                                                                                                                                                                              <p className="text-small text-text-secondary">
                                                                                                                                                                                                                                                                                                                                                                                                    {dt(e.date)} {cashBoxName(e.cashBoxId) ? `• ${cashBoxName(e.cashBoxId)}` : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                            {e.notes && <p className="text-small text-text-secondary mt-1">{e.notes}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <span className="text-financial text-danger">{fmt(e.amount)} <span className="text-small">{currency}</span></span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex gap-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => openEdit(e)} className="p-2 text-info hover:bg-info/10 rounded-lg"><Edit2 size={16} /></button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => del(e.id)} className="p-2 text-danger hover:bg-danger/10 rounded-lg"><Trash2 size={16} /></button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Dialog open={open} onClose={handleClose} title={edit ? 'تعديل مصروف' : 'إضافة مصروف'}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="space-y-3 pb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* الصف الأول: نوع المصروف */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="block text-sm font-semibold text-text-primary mb-1">نوع المصروف</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <select value={f.title} onChange={e => handleChange('title', e.target.value)} className="input-field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {expenseTypes.map((t) => <option key={t} value={t}>{t}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* الصف الثاني: الصندوق */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="block text-sm font-semibold text-text-primary mb-1">الصندوق</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <select value={f.cashBoxId} onChange={e => handleChange('cashBoxId', e.target.value)} className="input-field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {s.cashBoxes.map((b: any) => <option key={b.id} value={b.id}>{b.name}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* الصف الثالث: المبلغ + التاريخ */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="grid grid-cols-2 gap-3">
<Input label="المبلغ" type="text" inputMode="decimal" value={f.amount ? fmt(+f.amount) : ''} onChange={e => handleChange('amount', e.target.value.replace(/,/g, ''))} />                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <Input label="التاريخ" type="date" value={f.date} onChange={e => handleChange('date', e.target.value)} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* الصف الرابع: الملاحظات */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Input label="الملاحظات" value={f.notes} onChange={e => handleChange('notes', e.target.value)} autoComplete="off" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Button fullWidth onClick={save}>{edit ? 'تحديث' : 'حفظ'}</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Dialog>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }