import { useState } from 'react';
import { useStore } from '@/store';
import Card from '@/components/ui/Card';
import SearchInput from '@/components/ui/SearchInput';
import EmptyState from '@/components/ui/EmptyState';

const fmt = (n: number) => Math.round(n).toLocaleString('en-US');
const dt = (d: string) => new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: '2-digit', day: '2-digit' });

export default function Inventory() {
  const s = useStore();
    const currency = s.settings?.currency || 'ريال يمني';
      const [search, setSearch] = useState('');

        const filtered = [...s.products].reverse().filter((p: any) => p.name.includes(search) || p.barcode.includes(search));

          const totalValue = filtered.reduce((sum: number, p: any) => sum + (p.stockQuantity || 0) * (p.lastPurchasePrice || p.purchasePrice || 0), 0);
            const totalItems = filtered.reduce((sum: number, p: any) => sum + (p.stockQuantity || 0), 0);

              const isLow = (p: any) => (p.stockQuantity || 0) <= (p.minStock || 20);
                const isOld = (p: any) => {
                    if (!p.createdAt) return false;
                        return Date.now() - new Date(p.createdAt).getTime() > 180 * 24 * 60 * 60 * 1000;
                          };

                            const lowStock = filtered.filter(isLow);
                              const oldStock = filtered.filter(isOld);

                                const formatStock = (p: any) => {
                                    const qty = p.stockQuantity || 0;
                                        if (p.unit === 'كرتون' && p.boxQty) {
                                              const cartons = Math.floor(qty / p.boxQty);
                                                    const pieces = qty % p.boxQty;
                                                          return `${cartons} كرتون + ${pieces} حبة`;
                                                              }
                                                                  return `${fmt(qty)} حبة`;
                                                                    };

                                                                      return (
                                                                          <div className="page-container">
                                                                                <h1 className="page-title">المخزون</h1>

                                                                                      <div className="grid grid-cols-2 gap-3 mb-4">
                                                                                              <Card accent>
                                                                                                        <p className="text-small text-text-secondary">عدد المنتجات</p>
                                                                                                                  <p className="text-financial text-info">{filtered.length}</p>
                                                                                                                          </Card>
                                                                                                                                  <Card accent>
                                                                                                                                            <p className="text-small text-text-secondary">إجمالي الحبات</p>
                                                                                                                                                      <p className="text-financial text-primary">{fmt(totalItems)}</p>
                                                                                                                                                              </Card>
                                                                                                                                                                      <Card accent>
                                                                                                                                                                                <p className="text-small text-text-secondary">قيمة المخزون</p>
                                                                                                                                                                                          <p className="text-financial text-success">{fmt(totalValue)} <span className="text-small">{currency}</span></p>
                                                                                                                                                                                                  </Card>
                                                                                                                                                                                                          <Card accent className="!border-r-warning">
                                                                                                                                                                                                                    <p className="text-small text-text-secondary">منخفضة المخزون</p>
                                                                                                                                                                                                                              <p className="text-financial text-warning">{lowStock.length}</p>
                                                                                                                                                                                                                                      </Card>
                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                  <SearchInput value={search} onChange={setSearch} placeholder="بحث عن منتج..." />

                                                                                                                                                                                                                                                        {oldStock.length > 0 && (
                                                                                                                                                                                                                                                                <div className="mb-4">
                                                                                                                                                                                                                                                                          <h3 className="text-card-title text-warning mb-2">⏰ منتجات في المخزون أكثر من 6 أشهر</h3>
                                                                                                                                                                                                                                                                                    {oldStock.map((p: any) => (
                                                                                                                                                                                                                                                                                                <Card key={p.id} className="mb-2 !border-r-warning">
                                                                                                                                                                                                                                                                                                              <div className="flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                <span className="font-semibold">{p.name}</span>
                                                                                                                                                                                                                                                                                                                                                                  <p className="text-small text-text-secondary">منذ {dt(p.createdAt)}</p>
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-small text-warning font-bold">قديم</span>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                            </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                          {lowStock.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-card-title text-danger mb-2">⚠️ منتجات منخفضة المخزون</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {lowStock.map((p: any) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Card key={p.id} className="mb-2 !border-r-danger">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex justify-between items-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="font-semibold">{p.name}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-small text-text-secondary">{p.barcode || '-'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="text-financial text-danger">{fmt(p.stockQuantity || 0)} حبة</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {filtered.length === 0 ? <EmptyState message="لا توجد منتجات في المخزون" /> : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {filtered.map((p: any) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const stockValue = (p.stockQuantity || 0) * (p.lastPurchasePrice || p.purchasePrice || 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const profit = (p.sellingPrice || 0) - (p.lastPurchasePrice || p.purchasePrice || 0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Card key={p.id} accent className={isOld(p) ? '!border-r-warning' : ''}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-start justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 className="font-semibold text-body">{p.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-small text-text-secondary">{p.barcode || '-'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex items-center gap-3 mt-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-small text-text-secondary">آخر شراء: <span className="font-bold text-text-primary">{fmt(p.lastPurchasePrice || p.purchasePrice || 0)}</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-small text-text-secondary">البيع: <span className="font-bold text-text-primary">{fmt(p.sellingPrice || 0)}</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-small text-text-secondary mt-1">الربح: <span className={`font-bold ${profit >= 0 ? 'text-success' : 'text-danger'}`}>{fmt(profit)}</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {p.createdAt && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-small text-text-secondary mt-1">تاريخ الإضافة: {dt(p.createdAt)}{isOld(p) && <span className="text-warning font-bold mr-2">• أكثر من 6 أشهر</span>}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="text-left">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className={`text-financial ${isLow(p) ? 'text-danger' : 'text-success'}`}>{fmt(p.stockQuantity || 0)}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-small text-text-secondary">حبة</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {p.unit === 'كرتون' && p.boxQty && <p className="text-small text-text-secondary mt-1">{formatStock(p)}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-small text-info mt-1">القيمة: {fmt(stockValue)} <span className="text-small">{currency}</span></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }