import { useState } from 'react';
import { useStore } from '@/store';
import { usePreventLeave } from '@/hooks/usePreventLeave';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import SearchInput from '@/components/ui/SearchInput';
import Dialog from '@/components/ui/Dialog';
import BarcodeScanner from '@/components/ui/BarcodeScanner';
import EmptyState from '@/components/ui/EmptyState';
import { Plus, Edit2, Trash2, Scan } from 'lucide-react';

const fmt = (n: number) => Math.round(n).toLocaleString('en-US');
const LC = "block text-sm font-bold text-primary mb-1 border-r-4 border-primary pr-2";

export default function Products() {
  const s = useStore();
    const currency = s.settings?.currency || 'ريال يمني';
      const [search, setSearch] = useState('');
        const [open, setOpen] = useState(false);
          const [edit, setEdit] = useState<any>(null);
            const [f, setF] = useState({ name: '', barcode: '', unit: 'كرتون', boxQty: '', openingStock: '', purchasePrice: '', sellingPrice: '', minStock: '' });
              const [barcodeOpen, setBarcodeOpen] = useState(false);
                const [hasChanges, setHasChanges] = useState(false);

                  usePreventLeave(hasChanges);

                    const filtered = [...s.products].reverse().filter((p: any) => p.name.includes(search) || p.barcode.includes(search));

                      const reset = () => {
                          setF({ name: '', barcode: '', unit: 'كرتون', boxQty: '', openingStock: '', purchasePrice: '', sellingPrice: '', minStock: '' });
                              setEdit(null); setHasChanges(false);
                                };

                                  const openAdd = () => { reset(); setOpen(true); };
                                    const openEdit = (p: any) => {
                                        setEdit(p);
                                            setF({
                                                  name: p.name, barcode: p.barcode || '',
                                                        unit: p.unit || 'كرتون', boxQty: p.boxQty?.toString() || '',
                                                              openingStock: p.openingStock?.toString() || '',
                                                                    purchasePrice: p.purchasePrice?.toString() || '',
                                                                          sellingPrice: p.sellingPrice?.toString() || '',
                                                                                minStock: p.minStock?.toString() || '',
                                                                                    });
                                                                                        setHasChanges(true);
                                                                                            setOpen(true);
                                                                                              };

                                                                                                const handleChange = (field: string, value: string) => {
                                                                                                    setF({ ...f, [field]: value });
                                                                                                        setHasChanges(true);
                                                                                                          };

                                                                                                            const save = () => {
                                                                                                                if (!edit && s.products.find((p: any) => p.name === f.name)) { alert('يوجد منتج بنفس الاسم'); return; }
                                                                                                                    const boxQty = f.unit === 'كرتون' ? +f.boxQty || 1 : 0;
                                                                                                                        const openingStock = +f.openingStock || 0;
                                                                                                                            const purchasePrice = +f.purchasePrice || 0;
                                                                                                                                const sellingPrice = +f.sellingPrice || 0;
                                                                                                                                    const data = {
                                                                                                                                          name: f.name, barcode: f.barcode,
                                                                                                                                                unit: f.unit, boxQty,
                                                                                                                                                      stockQuantity: edit ? (edit.stockQuantity || 0) : openingStock,
                                                                                                                                                            openingStock, purchasePrice, sellingPrice,
                                                                                                                                                                  lastPurchasePrice: edit ? (edit.lastPurchasePrice || purchasePrice) : purchasePrice,
                                                                                                                                                                        minStock: +f.minStock || 20,
                                                                                                                                                                            };
                                                                                                                                                                                if (edit) s.updateProduct(edit.id, data);
                                                                                                                                                                                    else s.addProduct({ id: '', ...data, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
                                                                                                                                                                                        setOpen(false); reset();
                                                                                                                                                                                          };

                                                                                                                                                                                            const handleClose = () => {
                                                                                                                                                                                                if (hasChanges && !confirm('لديك تغييرات غير محفوظة. هل تريد المغادرة؟')) return;
                                                                                                                                                                                                    setOpen(false); reset();
                                                                                                                                                                                                      };

                                                                                                                                                                                                        const del = (id: string) => {
                                                                                                                                                                                                            if (confirm('سيتم نقل المنتج إلى سلة المحذوفات. متابعة؟')) s.deleteProduct(id);
                                                                                                                                                                                                              };

const handleBarcodeDetected = (barcode: string) => {
      setF({ ...f, barcode: barcode });
          setBarcodeOpen(false);
              const existing = s.products.find((p: any) => p.barcode === barcode);
                  if (existing) {
                        alert(`المنتج موجود: ${existing.name}`);
                            }
                              };

                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                <div className="page-container">
                                                                                                                                                                                                                                      <div className="flex items-center justify-between mb-4">
                                                                                                                                                                                                                                              <h1 className="page-title mb-0">المنتجات</h1>
                                                                                                                                                                                                                                                      <Button onClick={openAdd}><Plus size={20} />إضافة</Button>
                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                  <SearchInput value={search} onChange={setSearch} placeholder="بحث عن منتج..." />
                                                                                                                                                                                                                                                                        {!filtered.length ? <EmptyState message="لا توجد منتجات" /> : (
                                                                                                                                                                                                                                                                                <div className="space-y-3">
                                                                                                                                                                                                                                                                                          {filtered.map((p: any) => {
                                                                                                                                                                                                                                                                                                      const uc = p.purchasePrice || 0;
                                                                                                                                                                                                                                                                                                                  const profit = (p.sellingPrice || 0) - uc;
                                                                                                                                                                                                                                                                                                                              const cartonCount = p.unit === 'كرتون' && p.boxQty ? Math.floor((p.stockQuantity || 0) / p.boxQty) : 0;
                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                        <Card key={p.id} accent>
                                                                                                                                                                                                                                                                                                                                                                        <div className="flex items-start justify-between">
                                                                                                                                                                                                                                                                                                                                                                                          <h3 className="text-page-title text-text-primary">{p.name}</h3>
                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => openEdit(p)} className="flex items-center gap-1 px-3 py-1.5 bg-info/10 text-info rounded-btn text-small font-semibold"><Edit2 size={16} />تعديل</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => del(p.id)} className="flex items-center gap-1 px-3 py-1.5 bg-danger/10 text-danger rounded-btn text-small font-semibold"><Trash2 size={16} />حذف</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-small text-text-secondary mt-1">باركود: {p.barcode || '-'}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid grid-cols-2 gap-3 mt-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {p.unit === 'كرتون' ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-center bg-background rounded-xl p-3"><p className="text-body text-text-secondary">عدد الكراتين</p><p className="text-financial text-text-primary">{cartonCount}</p><p className="text-small text-text-secondary mt-1">سعة الكرتون {p.boxQty || 1} حبة</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-center bg-background rounded-xl p-3"><p className="text-body text-text-secondary">إجمالي الحبات</p><p className="text-financial text-success">{fmt(p.stockQuantity || 0)}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-center bg-background rounded-xl p-3"><p className="text-body text-text-secondary">المخزون</p><p className="text-financial text-text-primary">{fmt(p.stockQuantity || 0)} حبة</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-center bg-background rounded-xl p-3"><p className="text-body text-text-secondary">الوحدة</p><p className="text-financial text-text-primary">حبة</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-center bg-background rounded-xl p-3"><p className="text-body text-text-secondary">سعر الشراء</p><p className="text-financial text-primary">{fmt(p.lastPurchasePrice || p.purchasePrice || 0)}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-center bg-background rounded-xl p-3"><p className="text-body text-text-secondary">سعر البيع</p><p className="text-financial text-primary">{fmt(p.sellingPrice || 0)}</p></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-3 text-center bg-primary-light rounded-xl p-2"><span className={`text-body font-bold ${profit >= 0 ? 'text-success' : 'text-danger'}`}>ربح الحبة: {fmt(profit)}</span></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Dialog open={open} onClose={handleClose} title={edit ? 'تعديل منتج' : 'إضافة منتج'}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-4 pb-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div><label className={LC}>اسم المنتج</label><Input value={f.name} onChange={e => handleChange('name', e.target.value)} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <label className={LC}>الباركود</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Input value={f.barcode} onChange={e => handleChange('barcode', e.target.value)} className="flex-1" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button onClick={() => setBarcodeOpen(true)} className="flex items-center justify-center w-[48px] h-[48px] rounded-input border border-border bg-surface text-text-secondary hover:text-primary hover:border-primary transition-colors"><Scan size={22} /></button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="grid grid-cols-2 gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div><label className={LC}>الوحدة</label><select value={f.unit} onChange={e => handleChange('unit', e.target.value)} className="input-field"><option value="كرتون">كرتون</option><option value="حبة">حبة</option></select></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {f.unit === 'كرتون' && <div><label className={LC}>عدد الحبات في الكرتون</label><Input type="number" value={f.boxQty} onChange={e => handleChange('boxQty', e.target.value)} /></div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {!edit && <div><label className={LC}>الرصيد الافتتاحي (حبة)</label><Input type="number" value={f.openingStock} onChange={e => handleChange('openingStock', e.target.value)} /></div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="grid grid-cols-2 gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div><label className={LC}>سعر الشراء (حبة)</label><Input type="number" value={f.purchasePrice} onChange={e => handleChange('purchasePrice', e.target.value)} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div><label className={LC}>سعر البيع (حبة)</label><Input type="number" value={f.sellingPrice} onChange={e => handleChange('sellingPrice', e.target.value)} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div><label className={LC}>الحد الأدنى للتنبيه</label><Input type="number" value={f.minStock} onChange={e => handleChange('minStock', e.target.value)} /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button fullWidth onClick={save}>{edit ? 'تحديث' : 'حفظ'}</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Dialog>

<BarcodeScanner
  open={barcodeOpen}
    onClose={() => setBarcodeOpen(false)}
      onDetected={handleBarcodeDetected}
        onProductFound={(product: any) => {
            alert(`المنتج موجود: ${product.name} - المخزون: ${product.stockQuantity || 0} حبة`);
              }}
                onNewProduct={(info: any) => {
                    setF({
                          ...f,
                                name: info.name || '',
                                      barcode: info.barcode || '',
                                          });
                                              setBarcodeOpen(false);
                                                }}
                                                />                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }