import { useState } from 'react';
import { useStore } from '@/store';
import { usePreventLeave } from '@/hooks/usePreventLeave';
import Card from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import SearchInput from '@/components/ui/SearchInput';
import Dialog from '@/components/ui/Dialog';
import EmptyState from '@/components/ui/EmptyState';
import { Plus, Edit2, Trash2, Phone } from 'lucide-react';

const fmt = (n: number) => Math.round(n).toLocaleString('en-US');

export default function Suppliers() {
  const s = useStore();
    const currency = s.settings?.currency || 'ريال يمني';
      const [search, setSearch] = useState('');
        const [open, setOpen] = useState(false);
          const [edit, setEdit] = useState<any>(null);
            const [f, setF] = useState({ name: '', phone: '', address: '', notes: '' });
              const [hasChanges, setHasChanges] = useState(false);

                usePreventLeave(hasChanges);

                  const filtered = [...s.suppliers].reverse().filter((sup: any) => sup.name.includes(search) || sup.phone.includes(search));

                    const reset = () => { setF({ name: '', phone: '', address: '', notes: '' }); setEdit(null); setHasChanges(false); };
                      const openAdd = () => { reset(); setOpen(true); };

                        const openEdit = (sup: any) => {
                            setEdit(sup);
                                setF({ name: sup.name, phone: sup.phone, address: sup.address || '', notes: sup.notes || '' });
                                    setHasChanges(true);
                                        setOpen(true);
                                          };

                                            const handleChange = (field: string, value: string) => {
                                                setF({ ...f, [field]: value });
                                                    setHasChanges(true);
                                                      };

                                                        const save = () => {
                                                            if (!f.name) return;
                                                                if (!edit && s.suppliers.find((sup: any) => sup.name === f.name)) { alert('يوجد مورد بنفس الاسم'); return; }
                                                                    const data = { name: f.name, phone: f.phone, address: f.address, notes: f.notes };
                                                                        if (edit) s.updateSupplier(edit.id, data);
                                                                            else s.addSupplier({ id: '', ...data, balance: 0, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
                                                                                setOpen(false); reset();
                                                                                  };

                                                                                    const handleClose = () => {
                                                                                        if (hasChanges && !confirm('لديك تغييرات غير محفوظة. هل تريد المغادرة؟')) return;
                                                                                            setOpen(false); reset();
                                                                                              };

                                                                                                const del = (sup: any) => {
                                                                                                    const hasPurchases = s.purchases.some((p: any) => p.supplierId === sup.id);
                                                                                                        const hasMovements = s.cashMovements.some((m: any) => m.referenceId === sup.id && m.referenceType === 'manual');
                                                                                                            if (hasPurchases || hasMovements) {
                                                                                                                  alert('لا يمكن حذف المورد لوجود عمليات سابقة مرتبطة به. يمكنك تعديل الاسم فقط.');
                                                                                                                        return;
                                                                                                                            }
                                                                                                                                if (confirm('سيتم نقل المورد إلى سلة المحذوفات. متابعة؟')) s.deleteSupplier(sup.id);
                                                                                                                                  };

                                                                                                                                    return (
                                                                                                                                        <div className="page-container">
                                                                                                                                              <div className="flex items-center justify-between mb-4">
                                                                                                                                                      <h1 className="page-title mb-0">الموردين</h1>
                                                                                                                                                              <Button onClick={openAdd}><Plus size={20} />إضافة</Button>
                                                                                                                                                                    </div>
                                                                                                                                                                          <SearchInput value={search} onChange={setSearch} placeholder="بحث عن مورد..." />
                                                                                                                                                                                {filtered.length === 0 ? <EmptyState message="لا يوجد موردين" /> : (
                                                                                                                                                                                        <div className="space-y-3">
                                                                                                                                                                                                  {filtered.map((sup: any) => (
                                                                                                                                                                                                              <Card key={sup.id} accent>
                                                                                                                                                                                                                            <div className="flex items-start justify-between">
                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                              <h3 className="text-card-title">{sup.name}</h3>
                                                                                                                                                                                                                                                                                {sup.phone && <p className="text-small text-text-secondary flex items-center gap-1 mt-1"><Phone size={14} />{sup.phone}</p>}
                                                                                                                                                                                                                                                                                                  {sup.address && <p className="text-small text-text-secondary mt-1">{sup.address}</p>}
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                  <div className="flex gap-1">
                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => openEdit(sup)} className="flex items-center gap-1 px-3 py-1.5 bg-info/10 text-info rounded-btn text-small font-semibold"><Edit2 size={16} />تعديل</button>
                                                                                                                                                                                                                                                                                                                                                                      <button onClick={() => del(sup)} className="flex items-center gap-1 px-3 py-1.5 bg-danger/10 text-danger rounded-btn text-small font-semibold"><Trash2 size={16} />حذف</button>
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="mt-3 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className="text-small text-text-secondary">الرصيد {sup.balance > 0 ? 'له' : 'عليه'}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span className={`text-financial ${sup.balance > 0 ? 'text-success' : 'text-danger'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {fmt(Math.abs(sup.balance))} <span className="text-small">{currency}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Dialog open={open} onClose={handleClose} title={edit ? 'تعديل مورد' : 'إضافة مورد'}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="space-y-3 pb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Input label="الاسم" value={f.name} onChange={e => handleChange('name', e.target.value)} autoComplete="off" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Input label="الهاتف" type="tel" value={f.phone} onChange={e => handleChange('phone', e.target.value)} autoComplete="off" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Input label="العنوان" value={f.address} onChange={e => handleChange('address', e.target.value)} autoComplete="off" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Input label="الملاحظات" value={f.notes} onChange={e => handleChange('notes', e.target.value)} autoComplete="off" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Button fullWidth onClick={save}>{edit ? 'تحديث' : 'حفظ'}</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Dialog>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }