import { useState, useEffect, useRef } from 'react';
import { Html5Qrcode } from 'html5-qrcode';
import { useStore } from '@/store';
import { lookupBarcode } from '@/utils/barcodeApi';
import Dialog from './Dialog';
import Button from './Button';
import Input from './Input';
import Card from './Card';
import { Camera, Keyboard, Search, Loader2 } from 'lucide-react';

const fmt = (n: number) => Math.round(n).toLocaleString('en-US');

interface BarcodeScannerProps {
  open: boolean;
    onClose: () => void;
      onDetected: (barcode: string) => void;
        onProductFound?: (product: any) => void;
          onNewProduct?: (info: any) => void;
          }

          export default function BarcodeScanner({ open, onClose, onDetected, onProductFound, onNewProduct }: BarcodeScannerProps) {
            const s = useStore();
              const [error, setError] = useState('');
                const [manualMode, setManualMode] = useState(false);
                  const [manualBarcode, setManualBarcode] = useState('');
                    const [loading, setLoading] = useState(false);
                      const [foundProduct, setFoundProduct] = useState<any>(null);
                        const [newProductInfo, setNewProductInfo] = useState<any>(null);
                          const scannerRef = useRef<Html5Qrcode | null>(null);
                            const fileInputRef = useRef<HTMLInputElement>(null);

                              useEffect(() => {
                                  if (!open) return;
                                      if (manualMode) return;

                                          const startScanner = async () => {
                                                try {
                                                        const scanner = new Html5Qrcode('barcode-reader');
                                                                scannerRef.current = scanner;
                                                                        await scanner.start(
                                                                                  { facingMode: 'environment' },
                                                                                            { fps: 10, qrbox: { width: 250, height: 150 } },
                                                                                                      (text) => handleBarcode(text),
                                                                                                                () => {}
                                                                                                                        );
                                                                                                                              } catch (err: any) {
                                                                                                                                      const errorMsg = err?.message || err?.toString() || 'خطأ غير معروف';
                                                                                                                                              setError(`تعذر الوصول للكاميرا: ${errorMsg}`);
                                                                                                                                                    }
                                                                                                                                                        };

                                                                                                                                                            const timer = setTimeout(startScanner, 300);
                                                                                                                                                                return () => {
                                                                                                                                                                      clearTimeout(timer);
                                                                                                                                                                            stopAndClose();
                                                                                                                                                                                };
                                                                                                                                                                                  }, [open, manualMode]);

                                                                                                                                                                                    const stopAndClose = () => {
                                                                                                                                                                                        if (scannerRef.current) {
                                                                                                                                                                                              try {
                                                                                                                                                                                                      scannerRef.current.stop().then(() => scannerRef.current?.clear());
                                                                                                                                                                                                            } catch {}
                                                                                                                                                                                                                  scannerRef.current = null;
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                        };

                                                                                                                                                                                                                          const handleClose = () => {
                                                                                                                                                                                                                              stopAndClose();
                                                                                                                                                                                                                                  setFoundProduct(null);
                                                                                                                                                                                                                                      setNewProductInfo(null);
                                                                                                                                                                                                                                          onClose();
                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                              const handleBarcode = async (barcode: string) => {
                                                                                                                                                                                                                                                  setLoading(true);
                                                                                                                                                                                                                                                      setError('');

                                                                                                                                                                                                                                                          const localProduct = s.products.find((p: any) => p.barcode === barcode);
                                                                                                                                                                                                                                                              if (localProduct) {
                                                                                                                                                                                                                                                                    setFoundProduct(localProduct);
                                                                                                                                                                                                                                                                          setLoading(false);
                                                                                                                                                                                                                                                                                onDetected(barcode);
                                                                                                                                                                                                                                                                                      if (onProductFound) onProductFound(localProduct);
                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                    const info = await lookupBarcode(barcode);
                                                                                                                                                                                                                                                                                                        if (info) {
                                                                                                                                                                                                                                                                                                              setNewProductInfo(info);
                                                                                                                                                                                                                                                                                                                    setLoading(false);
                                                                                                                                                                                                                                                                                                                          onDetected(barcode);
                                                                                                                                                                                                                                                                                                                                if (onNewProduct) onNewProduct(info);
                                                                                                                                                                                                                                                                                                                                      return;
                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                              setNewProductInfo({ barcode, name: '', brand: '', image: '', quantity: '', category: '' });
                                                                                                                                                                                                                                                                                                                                                  setLoading(false);
                                                                                                                                                                                                                                                                                                                                                      onDetected(barcode);
                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                          const handleManualSubmit = () => {
                                                                                                                                                                                                                                                                                                                                                              if (manualBarcode) handleBarcode(manualBarcode);
                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
                                                                                                                                                                                                                                                                                                                                                                      const file = e.target.files?.[0];
                                                                                                                                                                                                                                                                                                                                                                          if (!file) return;

                                                                                                                                                                                                                                                                                                                                                                              setLoading(true);
                                                                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                                                                        const scanner = new Html5Qrcode('barcode-reader-scan');
                                                                                                                                                                                                                                                                                                                                                                                              let result = '';
                                                                                                                                                                                                                                                                                                                                                                                                    try { result = await scanner.scanFile(file, true); } catch {
                                                                                                                                                                                                                                                                                                                                                                                                            try { result = await scanner.scanFile(file, false); } catch {}
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                        await scanner.clear();
                                                                                                                                                                                                                                                                                                                                                                                                                              if (result) handleBarcode(result);
                                                                                                                                                                                                                                                                                                                                                                                                                                    else setError('لم يتم العثور على باركود في الصورة. تأكد من وضوح الباركود.');
                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                              setError('فشل قراءة الباركود من الصورة');
                                                                                                                                                                                                                                                                                                                                                                                                                                                  } finally {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (foundProduct) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Dialog open={open} onClose={handleClose} title="✅ المنتج موجود">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="space-y-3 pb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Card className="!bg-success/5 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-success font-bold text-body">{foundProduct.name}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p className="text-small text-text-secondary">باركود: {foundProduct.barcode}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-small text-text-secondary mt-1">المخزون: {foundProduct.stockQuantity || 0} حبة</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-small text-text-secondary">سعر البيع: {fmt(foundProduct.sellingPrice || 0)}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button fullWidth onClick={handleClose}>تم - متابعة</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Dialog>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (newProductInfo && newProductInfo.name) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Dialog open={open} onClose={handleClose} title="🆕 منتج جديد">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-3 pb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {newProductInfo.image && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <img src={newProductInfo.image} alt={newProductInfo.name} className="w-24 h-24 rounded-xl object-cover mx-auto" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Card className="!bg-info/5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="font-bold text-body">{newProductInfo.name}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {newProductInfo.brand && <p className="text-small text-text-secondary">العلامة: {newProductInfo.brand}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-small text-text-secondary">باركود: {newProductInfo.barcode}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {newProductInfo.quantity && <p className="text-small text-text-secondary">الوزن/الحجم: {newProductInfo.quantity}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-small text-text-secondary text-center">تم جلب البيانات. أكمل الإدخال في صفحة المنتجات.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button fullWidth onClick={handleClose}>حسناً</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Dialog>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (newProductInfo && !newProductInfo.name) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Dialog open={open} onClose={handleClose} title="❌ غير موجود">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="space-y-3 pb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-center text-text-secondary">المنتج غير موجود في قاعدة البيانات ولا في الإنترنت.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-center font-bold">الباركود: {newProductInfo.barcode}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-small text-text-secondary text-center">يمكنك إضافته يدوياً من صفحة المنتجات.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Button fullWidth onClick={handleClose}>حسناً</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Dialog>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Dialog open={open} onClose={handleClose} title="مسح الباركود">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-3 pb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="flex gap-2 mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => { setManualMode(false); setError(''); }} className={`flex-1 flex items-center justify-center gap-1 py-2 rounded-btn text-small font-semibold ${!manualMode ? 'bg-primary text-white' : 'bg-primary-light text-primary'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Camera size={16} />كاميرا
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={() => { setManualMode(true); setError(''); }} className={`flex-1 flex items-center justify-center gap-1 py-2 rounded-btn text-small font-semibold ${manualMode ? 'bg-primary text-white' : 'bg-primary-light text-primary'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Keyboard size={16} />يدوي
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {loading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex items-center justify-center gap-2 py-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Loader2 size={24} className="animate-spin text-primary" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className="text-small">جاري البحث...</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {error && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-danger/5 text-danger text-small p-3 rounded-lg text-center">{error}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {!manualMode ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div id="barcode-reader" className="w-full overflow-hidden rounded-card" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-small text-text-secondary text-center">أو</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Button fullWidth variant="secondary" onClick={() => fileInputRef.current?.click()}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Camera size={16} />اختيار صورة باركود من المعرض
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input ref={fileInputRef} type="file" accept="image/*" onChange={handleFileUpload} className="hidden" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Input label="رقم الباركود" type="text" value={manualBarcode} onChange={e => setManualBarcode(e.target.value)} onKeyDown={e => e.key === 'Enter' && handleManualSubmit()} placeholder="أدخل رقم الباركود..." autoFocus />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Button fullWidth onClick={handleManualSubmit}><Search size={16} />بحث عن الباركود</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div id="barcode-reader-scan" className="hidden" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Dialog>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }